# Generated by Django 5.2.1 on 2025-05-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dosen',
        ),
    ]
