# Generated by Django 5.2.1 on 2025-05-30 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('kelas', models.CharField(max_length=50)),
                ('angkatan', models.PositiveIntegerField()),
                ('jurusan', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dpa', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('semester', models.PositiveIntegerField()),
                ('ipk', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ukt', models.DecimalField(decimal_places=2, max_digits=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
