# Generated by Django 5.2.1 on 2025-05-31 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_nama', models.CharField(max_length=200)),
                ('_nim', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('kode_mk', models.CharField(max_length=10, unique=True)),
                ('sks', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_kuliah_diajar', to=settings.AUTH_USER_MODEL)),
                ('mahasiswa', models.ManyToManyField(related_name='mata_kuliah_diambil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tugas', models.CharField(max_length=200)),
                ('nilai', models.IntegerField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KelasPilihan',
            fields=[
                ('matakuliah_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matakuliah.matakuliah')),
                ('nilai', models.IntegerField(default=0)),
                ('presensi', models.IntegerField(default=0)),
                ('is_pilihan', models.BooleanField(default=True)),
                ('kuota_mahasiswa', models.IntegerField(default=40)),
                ('minimal_peserta', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Kelas Pilihan',
                'verbose_name_plural': 'Kelas Pilihan',
            },
            bases=('matakuliah.matakuliah',),
        ),
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertemuan_ke', models.IntegerField()),
                ('judul', models.CharField(max_length=200)),
                ('ringkasan', models.TextField()),
                ('tanggal', models.DateTimeField()),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matakuliah.matakuliah')),
            ],
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('tenggat', models.DateTimeField()),
                ('file_tugas', models.FileField(blank=True, null=True, upload_to='tugas/')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matakuliah.matakuliah')),
            ],
        ),
        migrations.CreateModel(
            name='KelasWajib',
            fields=[
                ('matakuliah_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matakuliah.matakuliah')),
                ('nilai', models.IntegerField(default=0)),
                ('presensi', models.IntegerField(default=0)),
                ('is_wajib', models.BooleanField(default=True)),
                ('prasyarat', models.ManyToManyField(blank=True, to='matakuliah.kelaswajib')),
            ],
            options={
                'verbose_name': 'Kelas Wajib',
                'verbose_name_plural': 'Kelas Wajib',
            },
            bases=('matakuliah.matakuliah',),
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('tidak_hadir', 'Tidak Hadir'), ('izin', 'Izin'), ('sakit', 'Sakit')], max_length=20)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matakuliah.matakuliah')),
            ],
            options={
                'unique_together': {('mahasiswa', 'mata_kuliah', 'tanggal')},
            },
        ),
        migrations.CreateModel(
            name='PengumpulanTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_jawaban', models.FileField(upload_to='jawaban_tugas/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('nilai', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matakuliah.tugas')),
            ],
            options={
                'unique_together': {('mahasiswa', 'tugas')},
            },
        ),
    ]
