# Generated by Django 5.2.1 on 2025-06-01 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matakuliah', '0002_remove_kelaswajib_matakuliah_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KelasPilihan',
            fields=[
                ('matakuliah_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matakuliah.matakuliah')),
                ('nilai', models.IntegerField(default=0)),
                ('presensi', models.IntegerField(default=0)),
                ('is_pilihan', models.BooleanField(default=True)),
                ('kuota_mahasiswa', models.IntegerField(default=40)),
                ('minimal_peserta', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Kelas Pilihan',
                'verbose_name_plural': 'Kelas Pilihan',
            },
            bases=('matakuliah.matakuliah',),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='_nim',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='KelasWajib',
            fields=[
                ('matakuliah_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matakuliah.matakuliah')),
                ('nilai', models.IntegerField(default=0)),
                ('presensi', models.IntegerField(default=0)),
                ('is_wajib', models.BooleanField(default=True)),
                ('prasyarat', models.ManyToManyField(blank=True, to='matakuliah.kelaswajib')),
            ],
            options={
                'verbose_name': 'Kelas Wajib',
                'verbose_name_plural': 'Kelas Wajib',
            },
            bases=('matakuliah.matakuliah',),
        ),
    ]
