# Generated by Django 5.2.1 on 2025-05-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadiri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='nip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='tanggal_mulai_kerja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
