# Generated by Django 5.2.1 on 2025-06-01 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datadiri', '0003_remove_atmin_angkatan_remove_atmin_dpa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atmin',
            name='nim',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='nim',
        ),
    ]
