# Generated by Django 5.2.1 on 2025-06-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadiri', '0004_remove_atmin_nim_remove_dosen_nim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='dpa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='ipk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='ukt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
