# Generated by Django 5.2.1 on 2025-06-01 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadiri', '0005_alter_mahasiswa_dpa_alter_mahasiswa_ipk_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='advanced_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dosen',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='current_semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='dosen_profile_photos/'),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nama',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nip',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dosen_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
