# Generated by Django 5.2.1 on 2025-06-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadiri', '0006_dosen_advanced_profile_completed_dosen_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='dummy_courses_generated',
            field=models.BooleanField(default=False),
        ),
    ]
