# Generated by Django 5.2.1 on 2025-06-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datadiri', '0007_dosen_dummy_courses_generated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='advanced_profile_completed',
            new_name='initial_profile_completed',
        ),
    ]
