# Generated by Django 5.2.1 on 2025-06-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadiri', '0008_rename_advanced_profile_completed_dosen_initial_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='initial_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='mahasiswa_profile_photos/'),
        ),
    ]
