# Generated by Django 5.2.1 on 2025-06-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadiri', '0009_mahasiswa_initial_profile_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='angkatan',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='jurusan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='kelas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
